name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Move to tools
      run: |
        cd ${{ github.workspace }}/tools

    - name: Cache Docker images
      uses: actions/cache@v2
      id: cache-docker
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/tools/docker-compose.yml') }}-${{ hashFiles('**/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Start containers
      run: |
       docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'
        echo "export FOLDER_PATH=$(pwd)/build-output" >> $GITHUB_ENV

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build-output

    - name: Checkout to new repo
      uses: actions/checkout@v2
      with:
        repository: Rikicavaz77/MTSS-Assignment-2
        token: ${{ secrets.UPLOAD_TOKEN }}

    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: .
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'Rikicavaz77'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        ls
        git add Candidatura
        git commit -m "[BOT] Caricamento PDF"
        git push    
            
    - name: Checkout back to original repo
      uses: actions/checkout@v2
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
