name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/src
        chmod +x *.sh
        ./compilescript.sh -a
      
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop

