name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Start Docker container
      run: docker-compose -f "tools/docker-compose.yml" up -d
      
    - name: Execute compile script
      run: |
        docker exec -it argo-docs-latexpdfbuilder-1 bash -c "cd /data && ./compilescript.sh -a"
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Compile LaTeX files and move PDFs"
        git push
