name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: List files in directory
      run: ls
      
    - name: Change directory to tools
      run: cd ./tools
      
    - name: Stop Docker Compose
      run: docker compose stop

