name: Test

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: cd ../tools & docker-compose up -d

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" stop
