name: Test

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: | 
        ls & 
        cd ./tools &
        docker-compose

    - name: Stop containers
      if: always()
      run: | 
        ls & 
        cd ./tools &
        docker-compose
