name: Build and Deploy (PDFs) on PR Merge

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Cache Docker
      uses: actions/cache@v4
      id: cache-docker
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/tools/docker-compose.yml') }}-${{ hashFiles('**/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Start Docker Container
      run: |
       cd ${{ github.workspace }}/tools
       docker compose up -d 

    - name: Compile Documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'
        echo "export FOLDER_PATH=$(pwd)/build-output" >> $GITHUB_ENV

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Docs
        path: build-output

    - name: Checkout Destination Repository
      uses: actions/checkout@v4
      with:
        repository: Rikicavaz77/MTSS-Assignment-2
        token: ${{ secrets.UPLOAD_TOKEN }}
        branch: main
        fetch-depth: 0

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: Docs
        path: .
    
    - name: Push Documents
      run: |
        git config --global user.name 'bot'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        git add Candidatura
        git commit -m "[BOT] Caricamento PDF"
        git push    
            
    - name: Checkout Back Source Repository
      uses: actions/checkout@v4
            
    - name: Stop Docker Container
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
