name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'

    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "riccardo.cavalli@studenti.unipd.it"
        git config --global user.name "Rikicavaz77"
        git remote add board git@github.com:Rikicavaz77/MTSS-Assignment-2.git
        ls
        mv build-output Docs
        git add .
        git commit -m "Compile LaTeX files and move PDFs"

    - name: Push changes to remote repository
      uses: ad-m/github-push-action@master
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        branch: master  # Il ramo a cui fare il push delle modifiche
        repository: Rikicavaz77/MTSS-Assignment-2
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Documentazione
        path: |
          build
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
