name: Build and Deploy
run-name: Build and Deploy (PDFs) on PR Merge

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Cache Docker
      uses: actions/cache@v4
      id: cache-docker
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/tools/docker-compose.yml') }}-${{ hashFiles('**/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Start Docker Container
      run: |
       cd ${{ github.workspace }}/tools
       docker compose up -d 

    - name: Compile Documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -d RTB'
        echo "export FOLDER_PATH=$(pwd)/build-output" >> $GITHUB_ENV

    - name: Push Documents (temp)
      run: |
       git config --global user.name 'github-actions'
       git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
       ls
       git add -f build-output/RTB
       git commit -m "add build-output"
       git push

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build-output

    #name: Imposta permessi sulla directory
      #: sudo node-gyp rebuild -g --unsafe-perm

    - name: Checkout Destination Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.UPLOAD_TOKEN }}
        repository: Rikicavaz77/MTSS-Assignment-2
        fetch-depth: 0
        user: token

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: .
    
    - name: Push Documents
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        git status 
        git add . 
        git commit -m "[BOT] Caricamento PDF"
        git log --max-count=3
        git push    
            
    - name: Checkout Back Source Repository
      uses: actions/checkout@v4

    - name: Remove Documents (temp)
      run: |
       git config --global user.name 'github-actions'
       git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
       ls
       git rm -r -f build-output/RTB
       git commit -m "rm build-output"
       git push
            
    - name: Stop Docker Container
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
