name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Change directory to tools
      run: | 
        cd ${{ github.workspace }}/tools
        ls ${{ github.workspace }}/tools

    - name: List files in directory
      run: ls
      
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        ls ${{ github.workspace }}/tools
        docker compose stop

