name: LaTeX Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up TeX environment
      uses: xu-cheng/latex-action@v2
      
    - name: Compile LaTeX files
      run: |
        ./compilescript.sh -a
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Compile LaTeX files and move PDFs"
        git push
