name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Docker images and data volumes
      uses: actions/cache@v2
      with:
        path: |
          /var/lib/docker
          /path/to/your/volumes
        key: ${{ runner.os }}-docker-cache-${{ hashFiles('{{ github.workspace }}/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-cache-

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'

    - name: Commit and push changes
      run: |
        git config --global user.name 'Rikicavaz77'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        ls
        git add .
        git commit -m "Compile LaTeX files and move PDFs"
        git push
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Documentazione
        path: |
          build
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop

