name: Build and Deploy
run-name: Build and Deploy (PDFs) on PR Merge

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Cache Docker
      uses: actions/cache@v3
      id: cache-docker
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/tools/docker-compose.yml') }}-${{ hashFiles('**/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Start Docker Container
      run: |
       cd ${{ github.workspace }}/tools
       docker compose up -d 

    - name: Compile Documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -d RTB'
        echo "export FOLDER_PATH=$(pwd)/build-output" >> $GITHUB_ENV

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Docs
        path: build-output

    - name: Checkout Destination Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.FINE_GRAINED_TOKEN }}
        repository: Rikicavaz77/MTSS-Assignment-2
        fetch-depth: 0
        path: ./temp-checkout

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: Docs
        path: .

    - name: Upload Documents
      continue-on-error: true
      run: |
       if [ -d "RTB" ]; then
         ls
         if [ -d "RTB/Verbali/Esterni" ]; then
           echo "ciao"
           rm -rf RTB/Verbali/Esterni
         fi
         mv RTB temp-checkout
       fi
       cd ./temp-checkout
    
    - name: Push Documents
      continue-on-error: true
      run: |
        cd ./temp-checkout
        git config --global user.name 'github-actions'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        git status 
        git add .
        git commit -m "[BOT] Caricamento PDF"
        git log --max-count=3
        git push -u origin
            
    - name: Checkout Back Source Repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
         
    - name: Stop Docker Container
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
