name: Test

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: | 
        ls & 
        cd ./tools &
        docker-compose up -d --builddocker-compose -f $DOCKER_COMPOSE_FILE up -d

    - name: Stop containers
      if: always()
      run: | 
        ls & 
        cd ./tools &
        run: docker compose stop
