name: Build and Deploy
run-name: Build and Deploy (PDFs) on PR Merge

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Cache Docker
      uses: actions/cache@v4
      id: cache-docker
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/tools/docker-compose.yml') }}-${{ hashFiles('**/tools/docker/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Start Docker Container
      run: |
       cd ${{ github.workspace }}/tools
       docker compose up -d 

    - name: Compile Documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -d RTB'
        echo "export FOLDER_PATH=$(pwd)/build-output" >> $GITHUB_ENV

    - name: Push Documents (temp)
      run: |
       git config --global user.name 'github-actions'
       git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
       git checkout -b temp
       git add -f build-output
       git commit -m "ciao"
       git push -u origin temp
       echo "SHA_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build-output

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: /home/runner/work/prova_build_latex/build-output
    - name: Download Facing Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.FINE_GRAINED_TOKEN }}
        repository: Rikicavaz77/MTSS-Assignment-2
    - name: Clean Artifacts
      continue-on-error: true
      run: |
        cd ../Docs/RTB
        ls
    - name: Clean Facing Repo RTB
      continue-on-error: true
      run: |
        find ./RTB -mindepth 1 ! -path './RTB/Verbali/Interni/*' -delete
    - name: Update Facing Repo
      run: |
        mkdir -p "./RTB" && cp -r ../build.output/RTB/* ./RTB/
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        git add .
        git commit -m "[BOT] Aggiornamento documentazione"
        git push

    - name: Checkout Back Source Repository
      uses: actions/checkout@v4
         
    - name: Stop Docker Container
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
